### ISSUE TITLE
How can I downgrade the version

### ISSUE THREAD

**Issue by AlbertMarashi** [nxfi777/SurrealDB-Railway#2]
A SurrealDB stable release introduced a severe bug in our application, is there any way to control the surrealdb version from the docker image?

If I wanted to create my own template, how would I go about doing that?

**Comment by nxfi777** [comment]
<img width="460" alt="SurrealDB Railway Source" src="https://github.com/nxfi777/SurrealDB-Railway/assets/127808926/00f5496f-a4c6-499f-85ac-688d7380b703">


Disconnect and add your desired version from [Dockerhub](https://hub.docker.com/r/surrealdb/surrealdb).

**Comment by AlbertMarashi** [comment]
Thank you @nxfi777 I realised that after writing this and forgot to close 🤣
